# Alacritty Configuration
# Terminal emulator configuration optimized for development
# Theme: Catppuccin Mocha (consistent with editor theme)

# Window configuration
window:
  # Window dimensions (changes require restart)
  dimensions:
    columns: 120
    lines: 40
  
  # Window position (changes require restart)
  # position:
  #   x: 0
  #   y: 0
  
  # Window padding
  padding:
    x: 8
    y: 8
  
  # Spread additional padding evenly around the terminal content
  dynamic_padding: true
  
  # Window decorations
  decorations: full
  
  # Background opacity
  opacity: 0.95
  
  # Startup mode (changes require restart)
  startup_mode: Windowed
  
  # Window title
  title: Alacritty
  
  # Window class (Linux/BSD only)
  class:
    instance: Alacritty
    general: Alacritty

# Scrolling configuration
scrolling:
  # Maximum number of lines in the scrollback buffer
  history: 10000
  
  # Scrolling distance multiplier
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "JetBrains Mono"
    style: Regular
  
  # Bold font face
  bold:
    family: "JetBrains Mono"
    style: Bold
  
  # Italic font face
  italic:
    family: "JetBrains Mono"
    style: Italic
  
  # Bold italic font face
  bold_italic:
    family: "JetBrains Mono"
    style: Bold Italic
  
  # Point size
  size: 13.0
  
  # Offset is the extra space around each character
  offset:
    x: 0
    y: 0
  
  # Glyph offset determines the locations of the glyphs within their cells
  glyph_offset:
    x: 0
    y: 0
  
  # Use built-in font fallback specified by freetype
  builtin_font_fallback: true

# Color scheme: Catppuccin Mocha
# Consistent with editor theme (DEV-003)
colors:
  # Default colors
  primary:
    background: '#1e1e2e'  # base
    foreground: '#cdd6f4'  # text
    dim_foreground: '#7f849c'  # overlay1
    bright_foreground: '#cdd6f4'  # text
  
  # Cursor colors
  cursor:
    text: '#1e1e2e'  # base
    cursor: '#f5e0dc'  # rosewater
  
  vi_mode_cursor:
    text: '#1e1e2e'  # base
    cursor: '#b4befe'  # lavender
  
  # Search colors
  search:
    matches:
      foreground: '#1e1e2e'  # base
      background: '#a6adc8'  # subtext0
    focused_match:
      foreground: '#1e1e2e'  # base
      background: '#a6e3a1'  # green
    footer_bar:
      foreground: '#1e1e2e'  # base
      background: '#a6adc8'  # subtext0
  
  # Keyboard regex hints
  hints:
    start:
      foreground: '#1e1e2e'  # base
      background: '#f9e2af'  # yellow
    end:
      foreground: '#1e1e2e'  # base
      background: '#a6adc8'  # subtext0
  
  # Selection colors
  selection:
    text: '#1e1e2e'  # base
    background: '#f5e0dc'  # rosewater
  
  # Normal colors
  normal:
    black:   '#45475a'  # surface1
    red:     '#f38ba8'  # red
    green:   '#a6e3a1'  # green
    yellow:  '#f9e2af'  # yellow
    blue:    '#89b4fa'  # blue
    magenta: '#f5c2e7'  # pink
    cyan:    '#94e2d5'  # teal
    white:   '#bac2de'  # subtext1
  
  # Bright colors
  bright:
    black:   '#585b70'  # surface2
    red:     '#f38ba8'  # red
    green:   '#a6e3a1'  # green
    yellow:  '#f9e2af'  # yellow
    blue:    '#89b4fa'  # blue
    magenta: '#f5c2e7'  # pink
    cyan:    '#94e2d5'  # teal
    white:   '#a6adc8'  # subtext0
  
  # Dim colors
  dim:
    black:   '#45475a'  # surface1
    red:     '#f38ba8'  # red
    green:   '#a6e3a1'  # green
    yellow:  '#f9e2af'  # yellow
    blue:    '#89b4fa'  # blue
    magenta: '#f5c2e7'  # pink
    cyan:    '#94e2d5'  # teal
    white:   '#bac2de'  # subtext1
  
  # Indexed Colors
  indexed_colors:
    - { index: 16, color: '#fab387' }  # peach
    - { index: 17, color: '#f5e0dc' }  # rosewater

# Bell configuration
bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'
  command: None

# Background opacity
# window.opacity: 0.95

# Selection
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

# Cursor style
cursor:
  style:
    shape: Block
    blinking: Off
  
  vi_mode_style:
    shape: Block
    blinking: Off
  
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

# Live config reload
live_config_reload: true

# Shell program
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory
working_directory: None

# Window title dynamic updates
window.dynamic_title: true

# Performance optimizations
debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false

# Key bindings
key_bindings:
  # Terminal functionality
  - { key: V,         mods: Command,         action: Paste                         }
  - { key: C,         mods: Command,         action: Copy                          }
  - { key: H,         mods: Command,         action: Hide                          }
  - { key: M,         mods: Command,         action: Minimize                      }
  - { key: Q,         mods: Command,         action: Quit                          }
  - { key: W,         mods: Command,         action: Quit                          }
  - { key: N,         mods: Command,         action: SpawnNewInstance              }
  
  # Font size adjustment
  - { key: Plus,      mods: Command,         action: IncreaseFontSize              }
  - { key: Minus,     mods: Command,         action: DecreaseFontSize              }
  - { key: Key0,      mods: Command,         action: ResetFontSize                 }
  
  # Scrolling
  - { key: PageUp,    mods: Shift,           action: ScrollPageUp,   mode: ~Alt    }
  - { key: PageDown,  mods: Shift,           action: ScrollPageDown, mode: ~Alt    }
  - { key: Home,      mods: Shift,           action: ScrollToTop,    mode: ~Alt    }
  - { key: End,       mods: Shift,           action: ScrollToBottom, mode: ~Alt    }
  
  # Search
  - { key: F,         mods: Command,         action: SearchForward                 }
  - { key: B,         mods: Command,         action: SearchBackward                }
  
  # Tab functionality (tmux-style)
  - { key: T,         mods: Command,         chars: "\x02c"                        }
  - { key: Key1,      mods: Command,         chars: "\x021"                        }
  - { key: Key2,      mods: Command,         chars: "\x022"                        }
  - { key: Key3,      mods: Command,         chars: "\x023"                        }
  - { key: Key4,      mods: Command,         chars: "\x024"                        }
  - { key: Key5,      mods: Command,         chars: "\x025"                        }
  - { key: Key6,      mods: Command,         chars: "\x026"                        }
  - { key: Key7,      mods: Command,         chars: "\x027"                        }
  - { key: Key8,      mods: Command,         chars: "\x028"                        }
  - { key: Key9,      mods: Command,         chars: "\x029"                        }
  
  # Clear screen
  - { key: K,         mods: Command,         chars: "\x0c"                         }

# Mouse configuration
mouse:
  hide_when_typing: false
  
  bindings:
    - { mouse: Middle, action: PasteSelection }

# URL launching
url:
  launcher:
    program: open
    args: []
  
  modifiers: None

# Environment variables
env:
  TERM: alacritty
  COLORTERM: truecolor 